services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pwd
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: ./_docker/php/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./migrations.json:/var/www/html/migrations.json
      - ./OH.png:/var/www/html/OH.png
      - ./style.css:/var/www/html/style.css
      - ./tests:/var/www/html/tests
    depends_on:
      - database
    networks:
      - net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8085:80"

networks:
  net:
    driver: bridge
